### ISSUE TITLE
Error: Expected closing parenthesis.

### ISSUE THREAD

**Issue by nonlux** [postcss/postcss-selector-parser#116]
I try to  minify [normalize.css](https://github.com/necolas/normalize.css). And my build fail with error:
```
  Module build failed: Error: Expected closing parenthesis.
        at new error (postcss-selector-parser/dist/processor.js:29:23)
        at Parser.error (postcss-selector-parser/dist/parser.js:234:15)
        at Parser.parentheses (postcss-selector-parser/dist/parser.js:303:22)
        at Parser.parse (postcss-selector-parser/dist/parser.js:533:22)
        at Parser.loop (postcss-selector-parser/dist/parser.js:519:18)
        at new Parser (postcss-selector-parser/dist/parser.js:104:21)
        at Processor.process (postcss-selector-parser/dist/processor.js:26:21)
```
I debug and find bad selector: `svg:not(.\:root\)`
normalize.css code:
```
svg:not(:root) {
  overflow: hidden;
}
```
I remove it and build done.

After that I split code into two files.
 - normalize.css (with out svg rule)
 - additional.css (only svg rule)
Build done.

**Comment by chriseppstein** [comment]
I can't reproduce this issue: https://github.com/postcss/postcss-selector-parser/commit/2ff28b591ea960ffd8d3f74652df1348b374c913

**Comment by nonlux** [comment]
On next week I try to create test case for this.
