### ISSUE TITLE
Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by Morishiri** [postcss/postcss-selector-parser#124]
Hi,

While executing `lesshint` (`gulp-lesshint` to be exact) I managed to get this kind of error:
`Error: TypeError: Cannot read property 'value' of undefined`

The problem is that this is really huge project and I cannot separate the case where this happens so I can't provide minumum reproductible example.

I managed to find the place where error probably occures in `parser.js` file.

It's here:
```
if (last && last.type === types.PSEUDO) {
    var selector = new _selector2.default();
    var cache = this.current;
    last.append(selector);
    this.current = selector;
    while (this.position < this.tokens.length && balanced) {
        if (this.currToken[0] === tokens.openParenthesis) {
            balanced++;
        }
        if (this.currToken[0] === tokens.closeParenthesis) {
            balanced--;
        }
        if (balanced) {
            this.parse();
        } else {
            selector.parent.source.end.line = this.currToken[3];
            selector.parent.source.end.column = this.currToken[4];
            this.position++;
        }
    }
    this.current = cache;
} else {
    last.value += '(';
    while (this.position < this.tokens.length && balanced) {
        if (this.currToken[0] === tokens.openParenthesis) {
            balanced++;
        }
        if (this.currToken[0] === tokens.closeParenthesis) {
            balanced--;
        }
        last.value += this.parseParenthesisToken(this.currToken);
        this.position++;
    }
}
if (balanced) {
    return this.expected('closing parenthesis', this.currToken[5]);
}
```
It allows entering to `else` when `last` is `undefined`. But in `else` statement - `last` is used. That causes the problem. Can anyone who is more experienced in `less` check this issue and maybe find out what is the reason that this happens?

Full stacktrace:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: TypeError: Cannot read property 'value' of undefined
    at Parser.parentheses (/path/to/project/node_modules/lesshint/node_modules/postcss-selector-parser/dist/parser.js:456:17)
    at Parser.parse (/path/to/project/node_modules/lesshint/node_modules/postcss-selector-parser/dist/parser.js:632:22)
    at Parser.loop (/path/to/project/node_modules/lesshint/node_modules/postcss-selector-parser/dist/parser.js:618:18)
    at new Parser (/path/to/project/node_modules/lesshint/node_modules/postcss-selector-parser/dist/parser.js:129:14)
    at Processor._root (/path/to/project/node_modules/lesshint/node_modules/postcss-selector-parser/dist/processor.js:47:22)
    at Processor._runSync (/path/to/project/node_modules/lesshint/node_modules/postcss-selector-parser/dist/processor.js:83:25)
    at Processor.astSync (/path/to/project/node_modules/lesshint/node_modules/postcss-selector-parser/dist/processor.js:121:21)
    at module.exports (/path/to/project/node_modules/lesshint/lib/utils/parse-selector.js:6:21)
    at Object.attributeQuotesLinter [as lint] (/path/to/project/node_modules/lesshint/lib/linters/attribute_quotes.js:15:27)
    at linters.forEach (/path/to/project/node_modules/lesshint/lib/linter.js:94:38)
    at Array.forEach (native)
    at Linter.checkNode (/path/to/project/node_modules/lesshint/lib/linter.js:81:22)
    at ast.root.walk (/path/to/project/node_modules/lesshint/lib/linter.js:185:22)
    at /path/to/project/node_modules/postcss-less/node_modules/postcss/lib/container.js:148:26
    at Root.each (/path/to/project/node_modules/postcss-less/node_modules/postcss/lib/container.js:114:22)
    at Root.walk (/path/to/project/node_modules/postcss-less/node_modules/postcss/lib/container.js:147:21)
    at Linter.lint (/path/to/project/node_modules/lesshint/lib/linter.js:184:27)
    at Lesshint.checkString (/path/to/project/node_modules/lesshint/lib/lesshint.js:110:29)
    at DestroyableTransform.through.obj.cb.emit.PluginError.showStack [as _transform] (/path/to/project/node_modules/gulp-lesshint/index.js:28:38)
    at DestroyableTransform.Transform._read (/path/to/project/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/path/to/project/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/path/to/project/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/path/to/project/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (/path/to/project/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at write (/path/to/project/node_modules/gulp/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/path/to/project/node_modules/gulp/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/path/to/project/node_modules/gulp/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:185:7)
    at emitReadable_ (/path/to/project/node_modules/gulp/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/path/to/project/node_modules/gulp/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/path/to/project/node_modules/gulp/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/path/to/project/node_modules/gulp/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (/path/to/project/node_modules/gulp/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at afterTransform (/path/to/project/node_modules/gulp/node_modules/readable-stream/lib/_stream_transform.js:101:12)
    at TransformState.afterTransform (/path/to/project/node_modules/gulp/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at DestroyableTransform.noop [as _transform] (/path/to/project/node_modules/gulp/node_modules/through2/through2.js:26:3)
```

**Comment by pmdartus** [comment]
Hi @Morishiri,

I was able to reproduce the issue if you are trying to parse a selector starting with a `(`. For example:

```js
var parser = require('postcss-selector-parser');
parser().processSync('(h1)');
```

[Live example](https://runkit.com/pmdartus/postcssselectorparser-issues-124)

**Comment by Morishiri** [comment]
Wow, great job. I will look for something like this in my project and I will confirm if it is the case there. I will come back with an answer tomorrow (in about 12 hours)

**Comment by donotknow** [comment]
I can reproduce this issue with multiple comma separated media queries, for example, here is a failing test case (for [lossy.js](https://github.com/postcss/postcss-selector-parser/blob/master/src/__tests__/lossy.js#L79)):

```
ava('@words - multiple', testLossy, '@media (min-width: 700px), (min-height: 400px)', '@media (min-width: 700px), (min-height: 400px)');
```
