### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Expected a pseudo-class or pseudo-element

### ISSUE THREAD

**Issue by maxcorbeau** [postcss/postcss-selector-parser#138]
I'm getting the below error when calling `postcss-selector-parser` as grunt task from [grunt-uncss](https://github.com/uncss/grunt-uncss).

```
Running "uncss:dist" (uncss) task
(node:10426) UnhandledPromiseRejectionWarning: Error: Expected a pseudo-class or pseudo-element.
  at Root._error (/path/to/node/node_modules/uncss/node_modules/postcss-selector-parser/dist/parser.js:137:24)
  at Root.error (/path/to/node/node_modules/uncss/node_modules/postcss-selector-parser/dist/selectors/root.js:43:25)
  at Parser.error (/path/to/node/node_modules/uncss/node_modules/postcss-selector-parser/dist/parser.js:392:25)
  at Parser.expected (/path/to/node/node_modules/uncss/node_modules/postcss-selector-parser/dist/parser.js:685:25)
  at Parser.pseudo (/path/to/node/node_modules/uncss/node_modules/postcss-selector-parser/dist/parser.js:500:25)
  at Parser.parse (/path/to/node/node_modules/uncss/node_modules/postcss-selector-parser/dist/parser.js:649:22)
  at Parser.loop (/path/to/node/node_modules/uncss/node_modules/postcss-selector-parser/dist/parser.js:618:18)
  at new Parser (/path/to/node/node_modules/uncss/node_modules/postcss-selector-parser/dist/parser.js:129:14)
  at Processor._root (/path/to/node/node_modules/uncss/node_modules/postcss-selector-parser/dist/processor.js:47:22)
  at Processor._runSync (/path/to/node/node_modules/uncss/node_modules/postcss-selector-parser/dist/processor.js:83:25)
  at Processor.processSync (/path/to/node/node_modules/uncss/node_modules/postcss-selector-parser/dist/processor.js:177:27)
  at /path/to/node/node_modules/uncss/src/lib.js:46:26
  at Array.map (<anonymous>:null:null)
  at css.walkRules (/path/to/node/node_modules/uncss/src/lib.js:135:64)
  at /path/to/node/node_modules/postcss/lib/container.js:237:28
  at /path/to/node/node_modules/postcss/lib/container.js:144:26
  at Root.each (/path/to/node/node_modules/postcss/lib/container.js:110:22)
  at Root.walk (/path/to/node/node_modules/postcss/lib/container.js:143:21)
  at Root.walkRules (/path/to/node/node_modules/postcss/lib/container.js:235:25)
  at getUsedSelectors (/path/to/node/node_modules/uncss/src/lib.js:134:9)
  at Promise.all.pages.map (/path/to/node/node_modules/uncss/src/lib.js:234:44)
  at Array.map (<anonymous>:null:null)
  at uncss (/path/to/node/node_modules/uncss/src/lib.js:234:30)
  at processWithTextApi (/path/to/node/node_modules/uncss/src/uncss.js:146:12)
  at <anonymous>:null:null
  at process._tickCallback (internal/process/next_tick.js:188:7)

(node:10426) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10426) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
```
I tested with:

- **nodejs**: `8.11.1` and `9.11.1`
- **postcss-selector-parser**: `3.1.1` and `4.0.0-rc.1` (which I made sure I replaced under `node_modules/uncss/node_modules/postcss-selector-parser/`)

**Any idea how to fix this?**

Thanks

**Comment by chriseppstein** [comment]
You've got a malformed selector somewhere. Probably there's a colon followed by something that's not an ident.

The error we throw has location information but it looks like uncss is swallowing that part. If they passed the location along it would be much easier for you to debug it.

**Comment by SharakPL** [comment]
@stylelint in vscode throws it during typing. Expected behaviour would be to simply mark the problematic code appropriately, not to throw an error. Should it be fixed here or within Stylelint?
