### ISSUE TITLE
node.walk is not a function

### ISSUE THREAD

**Issue by tristanpendergrass** [postcss/postcss-selector-parser#265]
Hello, I am using postcss with Parcel and Tailwind in my project and everything has been going smoothly until I tried to use a certain feature of Tailwind: it happens when I add the "group-hover" part to the following lines:

```
div
    [ class "group-focus:text-red-500 cursor-pointer"
    , onClick ActivateFeatureInput
    ]
    [ text "Add feature" ]
```

The output on the command line is:

```
C:\dev\som>npm run build

> build
> parcel build src/index.html --dist-dir dist --public-url /dist/

× Build failed.

@parcel/transformer-postcss: node.walk is not a function

  TypeError: node.walk is not a function
      at C:\dev\som\node_modules\tailwindcss\node_modules\postcss-selector-parser\dist\selectors\container.js:228:23
      at Selector.each
  (C:\dev\som\node_modules\tailwindcss\node_modules\postcss-selector-parser\dist\selectors\container.js:207:16)
      at Selector.walk
  (C:\dev\som\node_modules\tailwindcss\node_modules\postcss-selector-parser\dist\selectors\container.js:224:17)
      at C:\dev\som\node_modules\tailwindcss\node_modules\postcss-selector-parser\dist\selectors\container.js:228:23
      at Selector.each
  (C:\dev\som\node_modules\tailwindcss\node_modules\postcss-selector-parser\dist\selectors\container.js:207:16)
      at Selector.walk
  (C:\dev\som\node_modules\tailwindcss\node_modules\postcss-selector-parser\dist\selectors\container.js:224:17)
      at Selector.walkPseudos
  (C:\dev\som\node_modules\tailwindcss\node_modules\postcss-selector-parser\dist\selectors\container.js:300:17)
      at C:\dev\som\node_modules\tailwindcss\lib\util\formatVariantSelector.js:114:18
      at Root.each
  (C:\dev\som\node_modules\tailwindcss\node_modules\postcss-selector-parser\dist\selectors\container.js:207:16)
      at Object.finalizeSelector (C:\dev\som\node_modules\tailwindcss\lib\util\formatVariantSelector.js:113:9)


C:\dev\som>
```

Final details: I'm on Windows, Node version is `v17.0.1`, and I'll paste my dependency versions here for good measure:
```
{
  "devDependencies": {
    "@parcel/transformer-elm": "^2.6.2",
    "cssnano": "^4.1.10",
    "daisyui": "^2.20.0",
    "elm": "^0.19.1-5",
    "elm-format": "^0.8.5",
    "elm-hot": "^1.1.2",
    "elm-test": "^0.19.1-revision4",
    "node-elm-compiler": "^5.0.4",
    "parcel": "^2.6.2",
    "parcel-bundler": "^1.12.5",
    "postcss": "^8.4.14",
    "sass": "^1.23.3",
    "tailwindcss": "^3.1.6"
  },
}
```

**Comment by GoodGoodJM** [comment]
I have same issue

**Comment by magne4000** [comment]
Same issue, but not related to having `group-hover` class. Reverting to `tailwind @~3.0.24` solves the issue for me.

**Comment by Loosie94** [comment]
Same here, also using Daisy UI.
