### ISSUE TITLE
it is bug or not?

### ISSUE THREAD

**Issue by evilebottnawi** [postcss/postcss-selector-parser#61]
https://github.com/stylelint/stylelint/issues/1153
```scss
.foo {
    -moz-osx-font-smoothing: grayscale; // here need `;`
    .bar & {}
}
```
Output:
```shell
Error: Unexpected "space" found.
    at new error (/path/to/stylelint/node_modules/postcss-selector-parser/dist/processor.js:27:23)
    at Parser.error (/path/to/stylelint/node_modules/postcss-selector-parser/dist/parser.js:212:15)
    at Parser.pseudo (/path/to/stylelint/node_modules/postcss-selector-parser/dist/parser.js:320:18)
    at Parser.parse (/path/to/stylelint/node_modules/postcss-selector-parser/dist/parser.js:502:22)
    at Parser.loop (/path/to/stylelint/node_modules/postcss-selector-parser/dist/parser.js:470:18)
    at new Parser (/path/to/stylelint/node_modules/postcss-selector-parser/dist/parser.js:89:21)
    at Processor.process (/path/to/node_modules/postcss-selector-parser/dist/processor.js:24:21)
    at index.js:62:10
    at /path/to/stylelint/node_modules/postcss/lib/container.js:110:28
    at /path/to/node_modules/postcss/lib/container.js:73:26
```

**Comment by ben-eb** [comment]
It's not a valid CSS selector string, as referenced here; https://github.com/postcss/postcss-selector-parser/commit/0a14cc8e5d698bdd0038fefd4762303c7e0d27e6. The parser is complaining about the space in between the `:` and `grayscale` as it thinks it should be parsing a pseudo element.
